"""-

Revision ID: b0d949dc8ff0
Revises: 945e89a3b925
Create Date: 2024-02-11 21:34:52.562339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d949dc8ff0'
down_revision: Union[str, None] = '945e89a3b925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('purchase_details', 'price_at_purchase',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('purchase_history', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_history', 'total_amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchase_details', 'price_at_purchase',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
