"""Add new column to USER (voice_gen)

Revision ID: d58570502c68
Revises: d44b3dc38044
Create Date: 2024-03-02 19:40:11.294200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58570502c68'
down_revision: Union[str, None] = 'd44b3dc38044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_tokens_voice_gen', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_tokens_voice_gen')
    # ### end Alembic commands ###
